exclude:
  # top-level log
  - '*.log'
  # markdown files
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE.md
  - PULL_REQUEST_TEMPLATE.md
  - README.md
  # ruby dependency files
  - Gemfile*
  # KSS (style guide) config and template
  - kss-config.json
  - styleguide-template
  # just ignore the whole JS lib directory
  - lib
  # Node depenencies
  - node_modules
  - package.json
  # unit tests
  - test
  # webpack configuration
  - webpack.config.js
  # all of the source (unbuilt) JS files
  - js/src
  # shell and other scripts
  - '*.sh'
  - data/**/*.md
  - data/**/*.yml
  - data/all-production/*/*.?sv
  - data/bin
  - data/geo/input
  - data/gdp
  - data/jobs
  - lib
  - maps/lib
  # Makefiles
  - Makefile
  - '**/Makefile'
  # data tools and SQLite databases
  - '*.db*'
  - .env
  - data/**/*.csv
  - data/**/*.js
  - data/**/*.md
  - data/**/*.ndjson
  - data/**/*.sql
  - data/**/*.svg
  - data/env.example
  - data/README.md
  - data/company-revenue/input
  - data/geo/input
  - data/jobs/bls
  - data/land-stats
  - maps/data
  - maps/land/*.json
  # Exclude following, for speed purposes
  - _explore
  - _how-it-works
  - _case-studies
  - _downloads
  - styleguide
  - _includes/location
  - _states
