title: US EITI

sass:
  style: compressed

exclude:
- bin
- lib
- node_modules
- package.json
- routes.yml
- server.js
- show
- styles
- test
- views

collections:
  communities:
    output: true
    permalink: /communities/:community/
