title: USEITI

description: >
    USEITI is part of an international effort to promote open and accountable
    management of natural resources. This site provides data about how the U.S.
    manages extractive industries.

# permanent url, for use in meta references
url: https://useiti.doi.gov

# app version number
version: v2.1.3

beckley_api_key: LXJh2PKSC6zxY0YNuBRYgIj2JxSPcDwSPCZuHBG1

sass:
  style: nested
  sass_dir: _sass

exclude:
  # top-level log
  - '*.log'
  # markdown files
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE.md
  - PULL_REQUEST_TEMPLATE.md
  - README.md
  # ruby dependency files
  - Gemfile*
  # KSS (style guide) config and template
  - kss-config.json
  - styleguide-template
  # just ignore the whole JS lib directory
  - lib
  # Node depenencies
  - node_modules
  - package.json
  # unit tests
  - test
  # webpack configuration
  - webpack.config.js
  # all of the source (unbuilt) JS files
  - js/src
  # shell and other scripts
  - '*.sh'
  - data/**/*.md
  - data/**/*.yml
  - data/all-production/*/*.?sv
  - data/bin
  - data/geo/input
  - data/gdp
  - data/jobs
  - lib
  - maps/lib
  # Makefiles
  - Makefile
  - '**/Makefile'
  # data tools and SQLite databases
  - '*.db*'
  - .env
  - data/**/*.csv
  - data/**/*.js
  - data/**/*.md
  - data/**/*.ndjson
  - data/**/*.sql
  - data/**/*.svg
  - data/env.example
  - data/README.md
  - data/company-revenue/input
  - data/geo/input
  - data/jobs/bls
  - data/land-stats
  - maps/data
  - maps/land/*.json

include:
  - /build.log

gems:
  - jekyll-sitemap

collections:
  case-studies:
    output: true
    permalink: /case-studies/:path/
  downloads:
    output: true
    permalink: /downloads/:path/
  explore:
    output: true
    permalink: /explore/:path/
  federal-revenue-by-company:
    output: true
    permalink: /how-it-works/federal-revenue-by-company/:path/
  how-it-works:
    output: true
    permalink: /how-it-works/:path/
  offshore_areas:
    output: false
    # permalinks are defined in _offshore_areas/???.md
  offshore_regions:
    output: true
    permalink: /explore/:path/
  states:
    output: true
    permalink: /explore/:path/

defaults:
  - scope:
      path: ''
      type: federal-revenue-by-company
    values:
      layout: federal-revenue-by-company

  - scope:
      path: ''
      type: states
    values:
      layout: state-page

  - scope:
      path: ''
      type: offshore_regions
    values:
      layout: offshore-region

shruggie:
  - d8394cf27efbf8ae2f96ee12788eb257f4358a42
  - 11652cb6b75c1e914857a215e8f8eca7a599e0e0
  - 85f41ebb92208a3508c75114999a560ebd741690
  - 695ef693b0889d16e60e6d6fff06dc1c79db45d2
  - b8c37255d14dc7fc67f3eea0266ee4f94759066e
  - 145339f20b6b880c54391360223877511afd7d2a
  - df66d905fcd5151ade0387b48cf7789d3ba8203a
  - 6f4c9ff75ae1dc4fcbf8d547d7a855615a4fd9b6
  - 009f8804ce5413a0d2a604e9938dba635c6c6222
  - cc20376993abd596768c9c60ff456ad9f4fe8e7c
