/:
  view: index

/communities:
  view: comm-home
/communities/tar:
  view: communities/comm-tar
/communities/nor:
  view: communities/comm-nor

/resource_revenues:
  view: revenues-home
/resource_revenues/offshore_oil_gas:
  view: revenues/offshore_oil_gas
/resource_revenues/onshore_renewables:
  view: revenues/onshore_renewables

/locations:
  view: locations
/locations/onshore:
  redirect: /locations

/locations/onshore/:state.json:
  data: state
  api: state

/locations/onshore/:state/revenues.(csv|json):
  data: stateRevenues
  api:
    key: stateRevenues
    params:
      filter: true

/locations/onshore/:state:
  data:
    - state
    - counties
  view: state

/locations/onshore/:state/:county:
  data:
    - state
    - county
  view: county
/locations/offshore/:area:
  data: area
  view: offshore-area

/resources:
  view: resources
/resources/:resource:
  view: resource
/resources/:resource/:datatype:
  view: resource
/resources/:resource/:datatype/US:
  view: resource
/resources/:resource/:datatype/onshore/:state:
  data: [region, counties]
  view: resource
/resources/:resource/:datatype/onshore/:state/:county:
  data: [region, counties, county]
  view: resource
/resources/:resource/:datatype/offshore/:area:
  data: region
  view: resource

/styleguide:
  view: styleguide
