title: Selectors
status: draft
context:
  with-groups:
    - name: Regions
      options:
      - Alaska offshore region
      - Atlantic Ocean
      - Gulf of Mexico
      - Pacific Ocean
    - name: States
      options:
      - Alaska
      - Alabama
      - Arkansas
      - Arizona
      - California
      - Colorado
      - Connecticut
      - Washington, DC
      - Delaware
      - Florida
      - Georgia
      - Hawaii
      - Iowa
      - Idaho
      - Illinois
      - Indiana
      - Kansas
      - Kentucky
      - Louisiana
      - Massachusetts
      - Maryland
      - Maine
      - Michigan
      - Minnesota
      - Missouri
      - Mississippi
      - Montana
      - North Carolina
      - North Dakota
      - Nebraska
      - New Hampshire
      - New Jersey
      - New Mexico
      - Nevada
      - New York
      - Ohio
      - Oklahoma
      - Oregon
      - Pennsylvania
      - Rhode Island
      - South Carolina
      - South Dakota
      - Tennessee
      - Texas
      - Utah
      - Virginia
      - Vermont
      - Washington
      - Wisconsin
      - West Virginia
      - Wyoming
