title: Selectors
status: draft
context:
  include:
    default: A default value
    nationwide: true
    nationwide_url: nationwide.gov
    nationwide_title: nationwide
  site:
    states:
      - url: ak.gov
        title: AK
      - url: oh.gov
        title: OH
      - url: pa.gov
        type: PA
      - url: ca.gov
        type: CA
# collated: true
# default: default
# variants:
#   - name: default
#     context:
#       className: select
#       text: Light gray
#   - name: chart-selector
#     context:
#       className: chart-selector #not working
#       text: Chart green
#   - name: select-dark-gray
#     context:
#       className: select-dark-gray
#       text: Dark gray
